"""PySchellenberg - Python library for Schellenberg USB Funk-Stick."""

from .const import (
    # Device commands
    CMD_ALLOW_PAIRING,
    CMD_DOWN,
    # USB stick commands
    CMD_ECHO_OFF,
    CMD_ECHO_ON,
    CMD_ENTER_BOOTLOADER,
    CMD_ENTER_INITIAL,
    CMD_GET_DEVICE_ID,
    CMD_GET_PARAM_P,
    CMD_GET_PARAM_Q,
    CMD_GET_PARAM_V,
    CMD_GET_PARAM_W,
    CMD_GET_SG,
    CMD_GET_TRANSCEIVER,
    CMD_LED_BLINK_1,
    CMD_LED_BLINK_2,
    CMD_LED_BLINK_3,
    CMD_LED_BLINK_4,
    CMD_LED_BLINK_5,
    CMD_LED_BLINK_6,
    CMD_LED_BLINK_7,
    CMD_LED_BLINK_8,
    CMD_LED_BLINK_9,
    CMD_LED_OFF,
    CMD_LED_ON,
    CMD_MANUAL_DOWN,
    CMD_MANUAL_UP,
    CMD_PAIR,
    CMD_REBOOT,
    CMD_SET_LOWER_ENDPOINT,
    CMD_SET_UPPER_ENDPOINT,
    CMD_STOP,
    CMD_TRANSMIT,
    CMD_UP,
    CMD_VERIFY,
    # Motor events
    EVENT_STARTED_MOVING_DOWN,
    EVENT_STARTED_MOVING_UP,
    EVENT_STOPPED,
    # Constants
    PAIRING_DEVICE_ENUM_START,
    PAIRING_TIMEOUT,
    # Sensor status codes
    SENSOR_WINDOW_HANDLE_0,
    SENSOR_WINDOW_HANDLE_90,
    SENSOR_WINDOW_HANDLE_180,
    VERIFY_TIMEOUT,
)
from .protocol import DeviceEvent, SchellenbergProtocol, SchellenbergStick, StickStatus

__all__ = [
    # Main classes
    "SchellenbergStick",
    "SchellenbergProtocol",
    "DeviceEvent",
    "StickStatus",
    # Device commands
    "CMD_ALLOW_PAIRING",
    "CMD_DOWN",
    "CMD_MANUAL_DOWN",
    "CMD_MANUAL_UP",
    "CMD_PAIR",
    "CMD_SET_LOWER_ENDPOINT",
    "CMD_SET_UPPER_ENDPOINT",
    "CMD_STOP",
    "CMD_UP",
    # Motor events
    "EVENT_STARTED_MOVING_DOWN",
    "EVENT_STARTED_MOVING_UP",
    "EVENT_STOPPED",
    # Sensor status codes
    "SENSOR_WINDOW_HANDLE_0",
    "SENSOR_WINDOW_HANDLE_90",
    "SENSOR_WINDOW_HANDLE_180",
    # USB stick commands
    "CMD_ECHO_OFF",
    "CMD_ECHO_ON",
    "CMD_ENTER_BOOTLOADER",
    "CMD_ENTER_INITIAL",
    "CMD_GET_DEVICE_ID",
    "CMD_GET_PARAM_P",
    "CMD_GET_PARAM_Q",
    "CMD_GET_PARAM_V",
    "CMD_GET_PARAM_W",
    "CMD_GET_SG",
    "CMD_GET_TRANSCEIVER",
    "CMD_LED_BLINK_1",
    "CMD_LED_BLINK_2",
    "CMD_LED_BLINK_3",
    "CMD_LED_BLINK_4",
    "CMD_LED_BLINK_5",
    "CMD_LED_BLINK_6",
    "CMD_LED_BLINK_7",
    "CMD_LED_BLINK_8",
    "CMD_LED_BLINK_9",
    "CMD_LED_OFF",
    "CMD_LED_ON",
    "CMD_REBOOT",
    "CMD_TRANSMIT",
    "CMD_VERIFY",
    # Constants
    "PAIRING_DEVICE_ENUM_START",
    "PAIRING_TIMEOUT",
    "VERIFY_TIMEOUT",
]

__version__ = "0.1.0"
