name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: zip
        directory: custom_components/schellenberg_usb
        filename: schellenberg_usb.zip
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        draft: true
        generate_release_notes: true
        files: custom_components/schellenberg_usb/schellenberg_usb.zip